conflictdiff: Output error message to stderr.

diff --git a/conflictdiff b/conflictdiff
--- a/conflictdiff
+++ b/conflictdiff
@@ -158,7 +158,7 @@ while [ $# -gt 0 ] ; do
                     fipatch="$PAR"
                     ;;
                 *)
-                    echo "Error: Too many arguments."
+                    echo "Error: Too many arguments." >&2
                     exit 1
                     ;;
             esac
